Lab3
SamaritaninS/Android pull request #4
Opened 2021-02-15 11:12 UTC by SamaritaninS

2021-02-16 12:56 UTC, gmltA requested changes
I don't see gravatar support here.

2021-02-16 12:56 UTC, gmltA commented on lab3/app/src/main/java/com/example/battleships/Activity/BattleActivity.java
> +        }
User RecyclerView with adapter for this.

2021-02-17 12:47 UTC, SamaritaninS commented
Добавил поддержку Gravatar

2021-02-17 12:50 UTC, gmltA requested changes
![image](https://user-images.githubusercontent.com/138737/108206700-cbb97100-7137-11eb-9ff1-ce2e860fdc8a.png)

2021-02-17 13:10 UTC, SamaritaninS commented
Доисправил переключение между аватарками.

2021-02-17 19:33 UTC, SamaritaninS commented
Сделал возможность выбора между Gravatar и своим аватаром.

2021-02-18 14:28 UTC, gmltA requested changes
-

2021-02-18 14:29 UTC, gmltA approved these changes

2021-05-06 09:48 UTC, closed without merging